name : Build lorsqu'on push
on : push
jobs: 
  build:
    name: Build du projet exemple
    runs-on: ubuntu-latest
    steps: 
      - name : Récupérer le code
        uses : actions/checkout@v4
      - name : Installation des dépendances
        uses : npm i
      - name : Run build
        uses : npm run build